const state={isLoggedIn:false,activeTab:"dashboard",profile:{name:"",dob:"",weight:"",height:"",medications:[{name:"",frequency:"Once daily"}]},records:[{id:1,type:"BP",value:"130/85 mmHg",date:"2026-04-12",time:"08:00"},{id:2,type:"Sugar",value:"145 mg/dL",date:"2026-04-12",time:"08:05"}],ocrMode:"BP"};
function renderLogin(){return `<div class="login-page"><div class="login-card"><div class="login-brand"><img src="assets/logo.png" alt="logo" class="logo-large" /><p class="brand-subtitle">Health Tracker</p></div><button id="login-btn" class="btn btn-primary btn-block">Login</button></div></div>`}
function renderDashboard(){return `<div class="grid-2"><section class="card"><div class="card-body"><div class="overview-head"><div><p class="eyebrow">Overview</p><h2>Hello, User</h2><p>Your health snapshot for today.</p></div><div class="pill-box"><p class="eyebrow">Today</p><p>12 Apr 2026</p></div></div><div class="stat-grid"><div class="metric-card red-grad"><div class="metric-head"><div><p>Today's Blood Pressure</p><h3>130/85</h3><small>mmHg</small></div><div>❤</div></div></div><div class="metric-card pink-grad"><div class="metric-head"><div><p>Today's Blood Sugar</p><h3>145</h3><small>mg/dL</small></div><div>✚</div></div></div></div></div></section><section class="card"><div class="card-body"><div class="mini-stats"><div><p class="label">Today’s Blood Pressure</p><p class="value">130/85 mmHg</p></div><div><p class="label">Today’s Blood Sugar</p><p class="value">145 mg/dL</p></div><div class="next-reminder"><p class="label danger">Next Reminder</p><p class="value danger-text">8:00 AM · Take medication</p></div></div></div></section></div>`}
function renderProfile(){return `<section class="card"><div class="card-header">User Registration</div><div class="card-body"><div class="form-grid four"><input placeholder="Name"><input type="date"><input placeholder="Weight"><input placeholder="Height"></div><div class="form-grid two" style="margin-top:16px"><input placeholder="Medication name"><select><option>Once daily</option><option>Twice daily</option></select></div></div></section>`}
function renderRecord(){return `<div class="grid-2"><section class="card"><div class="card-header">Add Record</div><div class="card-body"><div class="form-grid two"><input placeholder="Systolic"><input placeholder="Diastolic"></div></div></section><section class="card"><div class="card-header">Camera Scan / OCR Flow</div><div class="card-body"><div class="scan-preview">Point camera at device screen</div></div></section></div>`}
function renderHistory(){return `<section class="card"><div class="card-header">History</div><div class="card-body"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Time</th><th>Type</th><th>Value</th></tr></thead><tbody>${state.records.map(r=>`<tr><td>${r.date}</td><td>${r.time}</td><td>${r.type}</td><td>${r.value}</td></tr>`).join("")}</tbody></table></div></div></section>`}
function renderTrends(){return `<div class="grid-2"><section class="card"><div class="card-header">Blood Pressure Trends</div><div class="card-body"><div class="chart-box"><div>04-12</div><div class="bar-bg"><div class="bar bar-red" style="width:65%"></div></div><div class="bar-bg"><div class="bar bar-pink" style="width:55%"></div></div></div></div></section><section class="card"><div class="card-header">Blood Sugar Trends</div><div class="card-body"><div class="chart-box"><div>04-12</div><div class="bar-bg"><div class="bar bar-red" style="width:72%"></div></div></div></div></section></div>`}
function renderMedications(){return `<section class="card"><div class="card-header">Medications</div><div class="card-body"><div class="list-row"><div><strong>Medication name</strong><p>Once daily</p></div><span class="badge-light">Reminder On</span></div></div></section>`}
function renderApp(){const content={dashboard:renderDashboard(),profile:renderProfile(),record:renderRecord(),history:renderHistory(),trends:renderTrends(),medications:renderMedications()}[state.activeTab];return `<div class="app-shell"><div class="top-grid"><section class="card"><div class="card-body"><div class="brand-row"><div class="logo-box"><img src="assets/logo.png" alt="logo"></div><div><p class="brand-subtitle">Health Tracker</p></div></div></div></section><section class="card"><div class="card-body"><div class="mini-stats"><div><p class="label">Today's Blood Pressure</p><p class="value">130/85 mmHg</p></div><div><p class="label">Today's Blood Sugar</p><p class="value">145 mg/dL</p></div></div></div></section></div><div class="tabs-bar">${["dashboard","profile","record","history","trends","medications"].map(tab=>`<button class="tab-btn ${state.activeTab===tab?"active":""}" data-tab="${tab}">${tab[0].toUpperCase()+tab.slice(1)}</button>`).join("")}</div>${content}</div>`}
function attach(){if(!state.isLoggedIn){document.getElementById("login-btn").onclick=()=>{state.isLoggedIn=true;render()};return}document.querySelectorAll("[data-tab]").forEach(btn=>btn.onclick=()=>{state.activeTab=btn.dataset.tab;render()})}
function render(){document.getElementById("app").innerHTML=state.isLoggedIn?renderApp():renderLogin();attach()}render();